### ISSUE TITLE
Error parsing ImmunoSeq files

### ISSUE THREAD

**Issue by ccasar** [antigenomics/vdjdb-server#20]
I've setup a local vdjdb-server and whenever I try to upload a sample file from ImmunoSeq the upload immediately throws an error:

[info] c.v.com - User vdjviz1@vdjviz.com: Error while rendering sample sample1

What kind of ImmunoSeq format does the server expect?

I tried ImmunoSeq v2 and v3, where the file headers are:

v2:
`nucleotide  aminoAcid count (templates) frequencyCount (%)  cdr3Length  vMaxResolved  vFamilyName vGeneName vGeneAllele vFamilyTies vGeneNameTies vGeneAlleleTies dMaxResolved  dFamilyName dGeneName dGeneAllele dFamilyTies dGeneNameTies dGeneAlleleTies jMaxResolved  jFamilyName jGeneName jGeneAllele jFamilyTies jGeneNameTies jGeneAlleleTies vDeletion n1Insertion d5Deletion  d3Deletion  n2Insertion jDeletion vIndex  n1Index dIndex  n2Index jIndex  estimatedNumberGenomes  sequenceStatus  cloneResolved vOrphon dOrphon jOrphon vFunction dFunction jFunction fractionNucleated`

v3:
`nucleotide  aminoAcid count (templates/reads) frequencyCount (%)  cdr3Length  vMaxResolved  vFamilyName vGeneName vGeneAllele vFamilyTies vGeneNameTies vGeneAlleleTies dMaxResolved  dFamilyName dGeneName dGeneAllele dFamilyTies dGeneNameTies dGeneAlleleTies jMaxResolved  jFamilyName jGeneName jGeneAllele jFamilyTies jGeneNameTies jGeneAlleleTies vDeletion n1Insertion d5Deletion  d3Deletion  n2Insertion jDeletion vIndex  n1Index dIndex  n2Index jIndex  estimatedNumberGenomes  sequenceStatus  cloneResolved vOrphon dOrphon jOrphon vFunction dFunction jFunction fractionNucleated vAlignLength  vAlignSubstitutionCount vAlignSubstitutionIndexes vAlignSubstitutionGeneThreePrimeIndexes vSeqWithMutations`

Or might there be something else wrong?

**Comment by mikessh** [comment]
Hello, this must be a problem with vdjtools parsing immunoseq files. Your file appears to be in ``v2`` format. I've just got latest sample exports in both immunoseq formats and I'm going to fix it.

The corresponding vdjtools issue is:
https://github.com/mikessh/vdjtools/issues/58

**Comment by ccasar** [comment]
Hi,
actually I was able to convert my current ImmunoSeq V3 files with vdjtools

`vdjtools.jar Convert -S immunoseq`

to generate vdj formatted files. But once I tried to upload them, I still got the same error.

**Comment by mikessh** [comment]
Hi, can you please test the latest release of VDJtools? 

https://github.com/mikessh/vdjtools/releases/tag/1.1.2

Your option should be ``-S immunoseqv2`` based on the column names you've provided. Don't use the files converted with Immunoseq V3, these might be converted incorrectly.

I'll update vdjdb-standalone (https://github.com/antigenomics/vdjdb-standalone) and vdjdb-server asap. Note that you can upload converted files (i.e. in VDJtools format) to vdjdb-server and vdjdb-standalone for analysis.

Please let me know if this helps.

**Comment by ccasar** [comment]
Hi,
actually I just realized, I opened this issue for the wrong project...I meant to open it for [vdj-viz](https://github.com/antigenomics/vdjviz). Should I reopen the issue over there?

Nonetheless I went back to immunoSEQ and exported our samples via 'Export Sample' (A) and 'Export Sample (v2)' (B) from the Project Overview.

I can't upload any of those samples via the vdjviz webinterface. When trying to convert files from A or B via vdjtools 1.1.2, only files from B with -S immunoseqv2 are successful all other combinations of A/B and -S immunoseq(v2) fail.
But even with the converted vdj files, I still receive an immediate error when trying to upload them via the vdjviz webinterface.

Additionally I tried your [example data](https://github.com/mikessh/vdjtools-examples/releases/tag/1.0), but the sample rendering fails for this dataset as well.

**Comment by mikessh** [comment]
VDJviz and VDJdb run with the same back-end. We'll update both of them with the new version of VDJtools that handles ImmunoSEQ parsing soon. As for now, you can get the latest version of VDJtools using the link I've provided in previous comment, convert all your files to VDJtools format and upload them to VDJviz/VDJdb using "VDJtools" as the input format.
